[package]
name = "to-html"
version = "0.1.3"
authors = ["Ludwig Stecher <ludwig.stecher@gmx.de>"]
description = "Render a terminal with ANSI colors as HTML"
categories = ["command-line-utilities"]
repository = "https://github.com/Aloso/to-html"
documentation = "https://docs.rs/to-html"
homepage = "https://github.com/Aloso/to-html"
readme = "README.md"
edition = "2021"
license = "MIT"
keywords = ["color", "cli", "terminal", "html"]
exclude = ["docs"]

[workspace]
members = ["crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake-tty = { path = "./crates/fake-tty", version = "0.3.1" }
ansi-to-html = { path = "./crates/ansi-to-html", version = "0.1.2" }
clap = { version = "4.1.10", features = ["derive"] }
dirs-next = "2.0.0"
logos = "0.12.1"
thiserror = "1.0.33"

[profile.dev.package."*"]
opt-level = 1

[profile.release]
lto = "thin"
