name: Test

on:
  push:
  pull_request:
  schedule:
    # Run monthly to keep Rust toolchain changes fresh
    - cron: '0 0 1 * *'

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [stable, beta]
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}
          components: rustfmt
      - uses: actions/checkout@v3
      - name: Run `cargo fmt`
        run: |
          cargo fmt --all -- --check

  clippy:
    needs: rustfmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [stable, beta]
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}
          components: clippy
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run `cargo clippy`
        run: |
          cargo clippy

  build:
    needs: clippy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        channel: [stable, beta]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and run tests
        run: |
          cargo test --verbose --workspace
